/**/mqtt_client:
  ros__parameters:
    broker:
      host: a1aovxuxlszpwl-ats.iot.us-east-1.amazonaws.com
      port: 8883
      tls:
        enabled: true
        ca_certificate: /greengrass/v2/rootCA.pem
    client:
      id: "test/raya_fleet_manager"
      clean_session: false
      tls:
        enabled: true
        certificate: /greengrass/v2/thingCert.crt
        key: /greengrass/v2/privKey.key
        version: 3
        verify: false
      buffer:
        size: 100000
      keep_alive_interval: 60.0
    bridge:
      ros2mqtt:
        ros_topics: 
          - /ping/ros
        /ping/ros:
          mqtt_topic: pingpong/ros
      mqtt2ros:
        mqtt_topics: 
          - pingpong/ros
        pingpong/ros:
          ros_topic: /pong/ros
