name: docker-ros

on: push

jobs:

  ros2:
    runs-on: ubuntu-latest
    steps:
      - uses: ika-rwth-aachen/docker-ros@main
        with:
          platform: amd64,arm64
          target: run
          image-tag: ros2
          enable-push-as-latest: 'true'
          base-image: rwthika/ros2:latest
          command: ros2 launch mqtt_client standalone.launch.ros2.xml
          enable-industrial-ci: 'true'
